export class Acceptance {
    id?: number;
    code?: string;
    name?: string;
    docNumber?: string;
    implementingUnit?: string;
    dateRecord?: Date;
    type?: number;
    note?: string;
    user?: string;
    result?: string;
    safe?: number;
    quality?: number;
    productivity?: number;
    actionMore?: string;
    responsibility?: string;
    limitation?: string;
    fromDateAcceptance?: Date;
    toDateAcceptance?: Date;
    fromDatePerform?: Date;
    toDatePerform?: Date;
    timeAcceptance?: Date;
    planDetailId?: number;
    status?: number;
    createdBy?: string;
    createdAt?: Date;
    updatedBy?: string;
    updatedAt?: Date;
    planResult?: any
    errorReport?: any;
    approvalWorkflow?: any;
    device?: any;
}
