spring.datasource.url=jdbc:mysql://localhost:3307/qltb?serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR
server.port=8081
#springdoc.pathsToMatch=/, /api/**
# C?u hình Keycloak
#keycloak.realm=demo-realm
#keycloak.auth-server-url=http://localhost:8080/
#keycloak.resource=spring-client
#keycloak.public-client=true
#keycloak.bearer-only=true

logging.level.org.springframework.security=DEBUG
logging.level.com.rd.project.qltb=DEBUG 
logging.level.root=INFO

#config keycloak new
# Keycloak OAuth2 Client configuration
#spring.security.oauth2.client.registration.keycloak.client-id=QLTB_test
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/auth/realms/jhipster
#spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak


# Resource server configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.68.90:8080/auth/realms/QLSX


#config keycloak new 2
# Keycloak OAuth2 Client configuration
spring.security.oauth2.client.registration.keycloak.client-id=QLTB_test
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://192.168.68.90:8080/auth/realms/QLSX
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak